# Generated by Django 4.2.4 on 2023-08-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_address_student_address_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='studentrecord',
        ),
    ]
